### ISSUE TITLE
Color theme and font in new REPL console

### ISSUE THREAD

**Issue by stakaz** [JunoLab/Juno.jl#104]
Hello, the new console looks horrible with a light theme. Half of the colors cannot be read ob the white background. Also the font is not my standard font for atom. How can I change it with my style.less? I have tried something like
```less
ink-terminal, .ink-terminal .terminal.xterm {
	font-family: 'Liberation Mono','Ubuntu Mono','DejaVu Sans Mono', monospace !important;
	line-height: @ui-font-size * 2 - 8 !important;
	font-size  : @console-font-size !important;
}
```

with different classes but nothing worked out. Whould be great if someone could help me...
